env:
  - USER=travis GO111MODULE=off

os:
  - osx

language: go

branches:
  only:
    - master

after_success:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  fast_finish: true
  include:
    - go: tip
      name: "go test coverage"
      script:
        - df -h
        - travis_wait make ci
        - travis_wait 20 bash scripts/travis.sh
    - go: tip
      name: "go lint"
      script: travis_wait make ci-lint